syntax = "proto3";
package message;

// ------------------------------------------
// 用户信息管理（User Management Service Server）
// ------------------------------------------
service UserService {
  rpc Register(RegisterReq) returns (RegisterRsp);        // 注册
  rpc Login(LoginReq) returns (LoginRsp);                 // 登录
  rpc ResetPass(ResetPassReq) returns (ResetPassRsp);     // 重置密码
  rpc GetVerifyCode(VerifyReq) returns (VerifyRsp);       // 获取验证码
}

// 注册
message RegisterReq {
  string username = 1;
  string email = 2;
  string password = 3;
  string code = 4;
}

message RegisterRsp {
  int32 error = 1;  // 0成功 1用户名重复 2邮箱重复
}

// 登录
message LoginReq {
  string email = 1;
  string password = 2;
}

message LoginRsp {
  int32 error = 1;
  int32 uid = 2;
  string token = 3;
}

// 重置密码
message ResetPassReq {
  string username = 1;
  string email = 2;
  string new_password = 3;
  string code = 4;
}

message ResetPassRsp {
  int32 error = 1;
}

// 验证码
message VerifyReq {
  string email = 1;
}

message VerifyRsp {
  int32 error = 1;
  string email = 2;
  string code = 3;
}

// ------------------------------
// 邮件服务（MailerServer）
// ------------------------------

service MailerService {
  rpc SendMail(SendMailReq) returns (SendMailRsp);
}

message SendMailReq {
  string email = 1;
  string code = 2;
}

message SendMailRsp {
  int32 error = 1;
}

// ------------------------------
// 状态调度服务（StatusServer）
// ------------------------------

service StatusService {
  rpc AllocatePushServer(AllocateReq) returns (AllocateRsp); // 分配推送节点
  rpc ReportLogin(LoginReportReq) returns (LoginReportRsp);  // 上报登录
}

message AllocateReq {
  int32 uid = 1;
}

message AllocateRsp {
  int32 error = 1;
  string host = 2;
  string port = 3;
  string token = 4;
}

message LoginReportReq {
  int32 uid = 1;
  string token = 2;
}

message LoginReportRsp {
  int32 error = 1;
}