[GateServer]
host = 127.0.0.1
port = 8080
[StatusServer]
host = 127.0.0.1
port = 50052
[Redis]
host = 127.0.0.1
port = 6379
password = 123456
[MySQL]
host = 127.0.0.1
port = 3306
user = root
password = password
dbName = oxytasks
# SegmentTree 使用线段树作节点负载均衡，时间复杂度O(logn)，适用于大型集群
# Brute 传统暴力遍历方法作节点负载均衡，时间复杂度O(N), 适用于小型集群
# methods = Brute 
[AllocateMethods]
methods = SegmentTree
[PushServers]
name = PushServer1,PushServer2
[PushServer1]
name = PushServer1
host = 127.0.0.1
port = 8890
gRPC_port = 50056
[PushServer2]
name = PushServer2
host = 127.0.0.1
port = 8891
gRPC_port = 50057
[Kafka]
brokers = 127.0.0.1:9092
topic = logs
[Log]
level = INFO
file_path = ../logs/
service_name = StatusServer
flush_interval = 5
max_buffer_size = 100
[Monitor]
heartbeat_timeout = 30
